### ISSUE TITLE
Azure region in short format for resource naming purpose?

### ISSUE THREAD

**Issue by mloskot** [Azure/terraform-azurerm-regions#14]
I have been using this simple yet amazingly useful module https://registry.terraform.io/modules/claranet/regions/azurerm/latest for quite some time and I really like its idea of reporting short name of a region which can be used for location-based naming, especially useful together with https://registry.terraform.io/providers/aztfmod/azurecaf/latest/docs/resources/azurecaf_name, for example

```hcl
module "azure_region" {
  source  = "claranet/regions/azurerm"
  version = "x.x.x"

  azure_region = var.azure_region
}

module "rg" {
  source  = "claranet/rg/azurerm"
  version = "x.x.x"

  location    = module.azure_region.location
  client_name = var.client_name
  environment = var.environment
  stack       = var.stack
}
```

where `module.rg.resource_group_name` outputs, for example: `rg-mloskot-uks-dev`

Would it be sensible/possible to add support for this format of short name to this module?

**Comment by BzSpi** [comment]
Hello @mloskot 

We talk (a lot) about it internally, this is a recurring topic.

To sum it up why we haven't done it (yet ?):
* resource group can contain resources from multiple regions even if not recommended
* it would be severely breaking since all resources would be destroyed during an update :grin: 

Also, it would make sense in case of applying the best practice of having all resources in a resource group in the same region.
Feel free to open a PR if you wish, but this behavior should not be breaking. Maybe having the `location_short` variable with a default `null` value ?

**Comment by matt-FFFFFF** [comment]
Thanks for this report.

You have raised this issue on the Azure/naming module, which is auto-generated from the locations and compute APIs.

I do not want to add any data to the module that is opinionated, that is to say it hasn't come from an Azure API.

Is there anything to do for this module or can I close this issue?

**Comment by mloskot** [comment]
Thanks @BzSpi and @matt-FFFFFF for the clarifications.

From my point, this can be closed for now.
